version: '3.8'

services:
  ceevee-supabase-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: supabase-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent storage for database
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  ceevee-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ceevee-api
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@ceevee-supabase-db:5432/supabase"
    ports:
      - "4000:4000"
    depends_on:
      ceevee-supabase-db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "yarn prisma migrate deploy && exec node dist/server.js"]

volumes:
  db_data:
    driver: local