services:
  ceevee-db:
    image: ceevee-db
    container_name: ceevee-db
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - path: ./db/.env
        required: false
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent storage for database
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  ceevee-api:
    image: ceevee-api
    container_name: ceevee-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - path: ./api/.env.docker
        required: false
    ports:
      - "4000:4000"
    depends_on:
      ceevee-db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "yarn prisma migrate deploy && exec node dist/server.js"]

volumes:
  db_data:
    driver: local