version: '3.8'

services:
  ceevee-supabase-db:
    build:
      context: ./db              # Build context points to the db folder
      dockerfile: Dockerfile     # Use Dockerfile from the db folder
    container_name: supabase-db  # Name of the database container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supabase
    ports:
      - "5432:5432" # Map the database to localhost:5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent storage for database

volumes:
  db_data:
    driver: local