name: 'Terraform CI'

on:
  pull_request:
    paths:
      - 'iac/**'
      - '.github/workflows/terraform-ci.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./iac

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.7.0'

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -diff
      continue-on-error: true

    - name: Post Format Results
      if: steps.fmt.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          const output = `#### Terraform Format Failed 🔴
          \`\`\`diff
          ${process.env.FMT_OUTPUT}
          \`\`\`
          Please run \`terraform fmt\` to fix formatting issues.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
      env:
        FMT_OUTPUT: ${{ steps.fmt.outputs.stdout }}

    - name: Terraform Init
      id: init
      run: terraform init -backend=false

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Post Validation Results
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const init = '${{ steps.init.outcome }}' === 'success' ? '✅' : '❌';
          const fmt = '${{ steps.fmt.outcome }}' === 'success' ? '✅' : '❌';
          const validate = '${{ steps.validate.outcome }}' === 'success' ? '✅' : '❌';
          
          const output = `### Terraform CI Results
          | Check | Status |
          |-------|--------|
          | Initialize | ${init} |
          | Format | ${fmt} |
          | Validate | ${validate} |`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
