name: 'Terraform CD'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - production

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'Deploy Infrastructure'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: ./iac

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.TERRAFORM_SA_EMAIL }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.11.0'

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.GCS_BUCKET }}" \
          -backend-config="prefix=${{ github.event.inputs.environment }}"

    - name: Terraform Plan
      run: |
        terraform plan \
          -var-file="environments/${{ github.event.inputs.environment }}.tfvars" \
          -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
